### ISSUE TITLE
Jetpack Compose integration

### ISSUE THREAD

**Issue by GrahamBorland** [badoo/RIBs#189]
I'm sure it's already on your radar, but I'd love to know what Jetpack Compose integration might look like. The current `RibView` interface is based on `ViewGroup`. Are there plans for an equivalent based on `@Composable`?

We can stick a `@Composable` hierarchy inside a `RibView` implementation and attach it to the `androidView` but I think this would only work in leaf nodes.

Or do you think that RIBs and Compose just wouldn't work nicely together at all?

I appreciate the work you're doing - thanks!

**Comment by zsoltk** [comment]
Hey @GrahamBorland ! Compose is definitely on our radar, and we'll want to use it when it becomes production ready. I've been thinking about how the two libraries can work together for a while now, and I agree it's not obvious. RIBs asks your view where to attach a child after it's been created and do it in an imperative way, whereas with Compose you'd want to define it upfront in a declarative way.

One way I imagine it could work is to open up the `RibView` interface a bit more, and allow actually implementing the attach child view part. In the case of Compose then it could trigger a recompose instead of a `ViewGroup` attach. I'll play around with it some more when I get to it.

**Comment by zsoltk** [comment]
We did an experiment: https://github.com/badoo/RIBs/tree/compose-experiment

It can definitely be improved on, but works as a proof of concept.

**Comment by zsoltk** [comment]
Compose support has been added.
